add compute nodes feature for existent cluster
RedHat-EMEA-SSA-Team/hetzner-ocp4 pull request #161
Opened 2020-12-21 09:21 UTC by rcarrata

## Description

Added the feature of create new compute nodes when the cluster is installed. The playbook uses the same worker.ign and the same structure, and it's retrocompatible with the existent compute nodes in the cluster.

## Checklist/ToDo's

- [Yes] Added documentation? (docs/add-compute-nodes.md)
- [Y] Added release note entry? (  docs/release-notes.md )
- [Y] Tested? Yes, ocp 4.6.8

```
# ansible-playbook ansible/05-add-compute.yml -e "compute_count=5"
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
Sunday 20 December 2020  20:50:14 +0100 (0:00:00.020)       0:00:00.020 *******
ok: [localhost]

TASK [openshift-4-cluster : Add new compute nodes ip and mac into the libvirt network] ****************************************************************************************************************************
Sunday 20 December 2020  20:50:15 +0100 (0:00:00.075)       0:00:01.125 *******
ok: [localhost] => (item=3)
changed: [localhost] => (item=4)

TASK [openshift-4-cluster : Create compute node] ******************************************************************************************************************************************************************
Sunday 20 December 2020  20:50:16 +0100 (0:00:00.832)       0:00:01.958 *******
included: /root/hetzner-ocp4/ansible/roles/openshift-4-cluster/tasks/create-vm.yml for localhost
included: /root/hetzner-ocp4/ansible/roles/openshift-4-cluster/tasks/create-vm.yml for localhost

TASK [openshift-4-cluster : Create disk for ocp4-compute-3] *******************************************************************************************************************************************************
Sunday 20 December 2020  20:50:16 +0100 (0:00:00.136)       0:00:02.094 *******
ok: [localhost]

TASK [openshift-4-cluster : Copy ignition ocp4-compute-3] *********************************************************************************************************************************************************
Sunday 20 December 2020  20:50:16 +0100 (0:00:00.348)       0:00:02.442 *******
ok: [localhost]

TASK [openshift-4-cluster : Define VirtualMachine ocp4-compute-3] *************************************************************************************************************************************************
Sunday 20 December 2020  20:50:17 +0100 (0:00:00.681)       0:00:03.124 *******
[WARNING]: 'xml' is given - ignoring 'name'
ok: [localhost]

TASK [openshift-4-cluster : Start VirtualMachine ocp4-compute-3] **************************************************************************************************************************************************
Sunday 20 December 2020  20:50:18 +0100 (0:00:00.454)       0:00:03.578 *******
ok: [localhost]

TASK [openshift-4-cluster : Create disk for ocp4-compute-4] *******************************************************************************************************************************************************
Sunday 20 December 2020  20:50:18 +0100 (0:00:00.305)       0:00:03.883 *******
changed: [localhost]

TASK [openshift-4-cluster : Copy ignition ocp4-compute-4] *********************************************************************************************************************************************************
Sunday 20 December 2020  20:50:18 +0100 (0:00:00.235)       0:00:04.119 *******
changed: [localhost]

TASK [openshift-4-cluster : Define VirtualMachine ocp4-compute-4] *************************************************************************************************************************************************
Sunday 20 December 2020  20:50:19 +0100 (0:00:00.610)       0:00:04.729 *******
changed: [localhost]

TASK [openshift-4-cluster : Start VirtualMachine ocp4-compute-4] **************************************************************************************************************************************************
Sunday 20 December 2020  20:50:19 +0100 (0:00:00.258)       0:00:04.988 *******
changed: [localhost]

TASK [openshift-4-cluster : Start background node approver process] ***********************************************************************************************************************************************
Sunday 20 December 2020  20:50:20 +0100 (0:00:00.616)       0:00:05.604 *******
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

# oc get nodes
NAME        STATUS   ROLES           AGE     VERSION
compute-0   Ready    worker          6h4m    v1.19.0+7070803
compute-1   Ready    worker          6h5m    v1.19.0+7070803
compute-2   Ready    worker          6h5m    v1.19.0+7070803
compute-3   Ready    worker          102m    v1.19.0+7070803
compute-4   Ready    worker          5m23s   v1.19.0+7070803
master-0    Ready    master,worker   6h13m   v1.19.0+7070803
master-1    Ready    master,worker   6h13m   v1.19.0+7070803
master-2    Ready    master,worker   6h13m   v1.19.0+7070803
```

2020-12-21 15:59 UTC, rbo requested changes
What's with the openshift-4-loadbalancer? We have to update too.

I like the approach:
1) Update `cluster.yml  ` to new compute_cound
2) Run an `update-compute.yml` playbook
sounds much easier than the add-node approach.

Just for information, I started an implementation too: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/tree/Issue88 but not with an update-compute approach.

Maybe can have a chat next day's or next year to finalize the idea.

2020-12-21 15:59 UTC, rbo commented on ansible/roles/openshift-4-cluster/tasks/add-compute.yml
> +  with_sequence: start=3 end="{{ compute_count|int - 1 }}" stride=1
The hardcoded start is not a good idea, because it could be less or more compute nodes available.

2020-12-21 15:59 UTC, rbo commented on ansible/roles/openshift-4-cluster/tasks/add-compute.yml
> +  with_sequence: start=3 end="{{ compute_count|int - 1 }}" stride=1
The hardcoded start is not a good idea, because it could be less or more compute nodes available.

2020-12-21 16:18 UTC, rcarrata commented on ansible/roles/openshift-4-cluster/tasks/add-compute.yml
> +  with_sequence: start=3 end="{{ compute_count|int - 1 }}" stride=1
Yes, fully agree with you. I through to check with the k8s ansible module, the real number of computes in order to obtain the start and the end of the sequence and always have a source of truth, avoiding the hardcoding one :)

2020-12-23 08:10 UTC, rbo commented
Let's discuss the feature in Issue #88 and create a new PR if every thing is done and tested.

2020-12-23 08:10 UTC, closed without merging