WIP: Gc add on
RedHat-EMEA-SSA-Team/hetzner-ocp4 pull request #280
Opened 2023-05-15 14:58 UTC by sluetze

## Description
added add-on role for garbagecollection

## Checklist/ToDo's

- [ ] Added documentation?
- [ ] Added release note entry? (  docs/release-notes.md )
- [ ] Tested?

2023-05-16 08:24 UTC, sluetze commented
fixed the lint errors. i obviously wasnt concentrated when building the branch and included some commits which are related to another PR. I close the other PR, since its quite small stuff

2023-06-10 06:18 UTC, rbo requested changes
Please remove tags `add-ons` let's just use `post-install` and `post-install-add-ons` thanks.

2023-06-10 06:18 UTC, rbo commented on ansible/roles/openshift-4-cluster/tasks/post-install-add-ons.yml
> +        - add-ons
Please remove `add-ons` let's just use `post-install` and `post-install-add-ons`.

2023-06-10 06:18 UTC, rbo commented on ansible/roles/openshift-4-cluster/tasks/post-install-add-ons.yml
> +    - add-ons
Please remove `add-ons` let's just use `post-install` and `post-install-add-ons`.

2023-09-28 09:34 UTC, rbo commented
/retest

2023-09-28 09:41 UTC, rbo commented
LGTM

2023-09-28 09:41 UTC, merged

2023-09-28 09:41 UTC, rbo commented
Thanks for contribution.